spring.datasource.url=jdbc:mysql://localhost/"Tu_Base_de_Datos"
spring.datasource.username=${DB_USER:"Tu_Usuario"}
spring.datasource.password=${DB_PASSWORD:"Tu_Contrasena"}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

api.security.secret=${JWT_SECRET:"Tu_clave_secreta}